from __future__ import annotations

import hashlib
import io
import locale
import marshal
import multiprocessing
import os
import pstats
import re
import shlex
import subprocess
import sys
import tempfile
import threading
import time
import statistics
from collections import Counter, defaultdict
from dataclasses import astuple, dataclass, field
from datetime import timedelta
from functools import cached_property
from typing import Iterable, List, Optional, TypeVar, Union

import click
import clickdc
from graphviz import Digraph
from tabulate import tabulate

from . import color
from .common import (
    click_help,
    qemu_output_drain_fifo,
    bash_cmd,
    bash_cmd_env,
)
from .compare import CompareArgs, compare_cmd

###############################################################################

T = TypeVar("T")
V = TypeVar("V")


def md5sum(data: str) -> str:
    return hashlib.md5(data.encode("utf-8")).hexdigest()


def clamp(n: int, minn: int, maxn: int) -> int:
    return max(min(maxn, n), minn)


def dots_trim(v: str, width: int = 50) -> str:
    """if string is too long, trim it and add dots"""
    return v if len(v) <= width else (v[: width - 2] + "..")


def file_newer(a: str, b: str) -> bool:
    return (
        os.path.exists(a)
        and os.path.exists(b)
        and os.path.getctime(a) > os.path.getctime(b)
    )


def maybe_take_n(generator: Iterable[T], n: Optional[int]) -> Iterable[T]:
    """If n is ok, then take up to n elements"""
    if n and n > 0:
        return (a for _, a in zip(range(n), generator))
    else:
        return generator


def getdefault(e: list[T], idx: int, default: V = None) -> T | V:
    try:
        return e[idx]
    except (KeyError, IndexError):
        return default


def us2s(us: int) -> float:
    return us / 1000000


def fmtus(us: int) -> str:
    return f"{us:f}s"


def flatten(x: list[list[T]]) -> Iterable[T]:
    return (item for sublist in x for item in sublist)


def asgroups(x: Iterable[T], n: int) -> Iterable[list[T]]:
    i = 1
    group: list[T] = []
    for line in x:
        group.append(line)
        if i == n:
            yield group
            group = []
            i = 1
        else:
            i += 1
    if group:
        yield group


###############################################################################


@dataclass
class Integer:
    v: int = 0

    def inc(self):
        self.v += 1
        return self.v - 1


@dataclass
class RedGreenHue:
    elems: int

    def color(self, idx: int) -> Optional[str]:
        if self.elems == 0:
            return None
        val = int(0xFF * 2 / self.elems * idx)
        color = "#%02x%02x%02x" % (
            0xFF - val if 0 <= val < 0xFF else 0x00,
            val - 0xFF if 0xFF <= val else 0x00,
            0x00,
        )
        return color


@dataclass(frozen=True, order=True)
class FunctionKey:
    """To uniquely identify a function."""

    filename: str = ""
    lineno: int = -1
    funcname: str = ""

    def __str__(self):
        return f"{self.filename}:{self.lineno}({self.funcname})"


@dataclass
class Record:
    """Single line output from profiling information. Represents one instruction"""

    idx: int
    """Instruction number"""
    stamp_us: int
    """The timestamp as generated by EPOCHREALTIME"""
    pid: int
    """$BASPID"""
    cmd: str
    """$BASH_COMMAND"""
    level: int
    """${#BASH_SOURCE[@]}"""
    lineno: int
    """$LINENO"""
    source: str
    """$BASH_SOURCE, might be empty"""
    funcname: str
    """$BASH_FUNCNAME, might be empty"""
    spent_us: int = -1
    """How long did the instruction take? Substraction of EPOCHREALTIME from the next instruction"""

    def function(self):
        return FunctionKey(self.source, self.lineno, self.funcname)


class Records(List[Record]):
    """An array of records"""

    @property
    def sum_spent_us(self):
        return sum(x.spent_us for x in self)


@dataclass
class CmdStats:
    cmd: str
    callcount: int = 0
    totaltime: int = 0


@dataclass
class CallgraphNode:
    """Single node in the callgraph tree"""

    function: FunctionKey = field(default_factory=FunctionKey)
    records: list[Union[Record, CallgraphNode]] = field(default_factory=list)
    parent: Optional[CallgraphNode] = None

    @property
    def key(self):
        return self.function

    @cached_property
    def level(self) -> int:
        return 1 + (self.parent.level if self.parent else -1)

    @cached_property
    def inlinetime(self) -> int:
        return sum(rr.spent_us for rr in self.records if isinstance(rr, Record))

    @cached_property
    def childtime(self) -> int:
        return sum(rr.totaltime for rr in self.records if isinstance(rr, CallgraphNode))

    @cached_property
    def records_cnt(self) -> int:
        return sum(
            rr.records_cnt if isinstance(rr, CallgraphNode) else 1
            for rr in self.records
        )

    @cached_property
    def totaltime(self) -> int:
        return self.inlinetime + self.childtime

    def strtree(self) -> str:
        return (
            self.parent.strtree() + "->" if self.parent else ""
        ) + f"{self.function}"

    @property
    def children(self) -> dict[FunctionKey, "CallgraphNode"]:
        res: dict[FunctionKey, "CallgraphNode"] = {}
        for rr in self.records:
            if isinstance(rr, CallgraphNode):
                res[rr.function] = rr
        return res


@dataclass
class AnalyzeArgs:
    """Command line arguments"""

    showtimes: Optional[bool] = clickdc.option(
        help="Show processing times in the output"
    )
    linelimit: Optional[int] = clickdc.option(
        help="From the input file, parse only that many lines from the top. This is used to reduce the numebr of analyzed lines for testing"
    )

    callgraph: Optional[str] = clickdc.option(
        help="Generate a DOT callgraph. Use a viewer like `xdot` to visualize the flow.",
    )
    callstats: Optional[str] = clickdc.option(
        help="Generate a DOT callgraph with function call statistics.",
    )
    callstatscmds: Optional[bool] = clickdc.option(
        help="Include individual commands in the callstats graph."
    )
    pstats: Optional[str] = clickdc.option(
        help="Generate a Python pstats file, compatible with the `cProfile` module for deep analysis."
    )
    dumprecords: Optional[str] = clickdc.option(
        help="Dump callgraph in text format to a file command by command, call by call.",
    )
    json: Optional[bool] = clickdc.option(
        "-j", "--json", is_flag=True, help="Output analysis results as JSON to stdout."
    )

    treelimit: Optional[int] = clickdc.option(
        default=3,
        show_default=True,
        help="""
        When generating ASCII call tree,
        limit the number of children of each point to max this number.
        """,
    )
    dotlimit: Optional[int] = clickdc.option(
        default=0,
        show_default=True,
        help="""
        When generating dot callgraph or callstats,
        limit the number of children of each point to max this number.
        Use to reduce big callgraphs where you do not see anything.
        """,
    )
    filterfunction: Optional[str] = clickdc.option(
        help="""
            Filter processing to callgraph roots from this function.
            Usefull for analysis of a single bash function execution
            """
    )
    qemu: Optional[bool] = clickdc.option(
        help="Use QEMU profiling mode logic. Counts Trace lines between MARKERs."
    )

    profilefile: io.TextIOBase = clickdc.argument(
        type=click.File(errors="replace", lazy=True),
        required=False,
        default=io.TextIOWrapper(sys.stdin.buffer, errors="ignore"),
    )


@dataclass
class RecordsSpentInterface:
    records: list[Record] = field(default_factory=list)
    spent: int = 0

    def add_record(self, rr: Record):
        self.records.append(rr)
        self.spent += rr.spent_us

    def get_example(self):
        if not self.records:
            return "~:0"
        cmdcnt = Counter(r.cmd for r in self.records)
        if not cmdcnt:
            r = self.records[0]
            return f"{r.source or '~'}:{r.lineno}"
        most_common_cmd: str = cmdcnt.most_common(1)[0][0]
        r: Record = next(r for r in self.records if r.cmd == most_common_cmd)
        return f"{r.source or '~'}:{r.lineno}"


@dataclass
class FunctionStats(RecordsSpentInterface):
    """Accumulated data about a single function"""

    calls: int = 0
    spent_exclusive: int = 0


@dataclass
class Timeit:
    """Measure time of a section"""

    name: str = ""
    start: float = 0
    duration: float = 0

    def __enter__(self):
        self.start = time.time()

    def __exit__(self, *_):
        self.duration = time.time() - self.start
        if self.name:
            self.print()

    def print(self):
        print(f"{self.name} took {timedelta(seconds=self.duration)} seconds")


@dataclass
class CommandStats(RecordsSpentInterface):
    """Accumulated data about a single command"""

    callers: Counter[str] = field(default_factory=Counter)

    def add(self, rr: Record):
        self.add_record(rr)
        self.callers.update([rr.funcname])


# List of bash scripts used for profiling.
PROFILEMETHODS: dict[str, str] = {
    "XTRACE": r"""
export BASH_XTRACEFD PS4='+ ${EPOCHREALTIME//[.,]} ${BASHPID:-${BASH_SUBSHELL:-$$}} ${#BASH_SOURCE[@]} ${LINENO:-0} ${BASH_SOURCE[0]:-<} ${FUNCNAME[0]:->} '
exec {BASH_XTRACEFD}>"$1"
shift
%BEFORE%
set -x
%SCRIPT%
: END
""",
    "DEBUG": r"""
set -T
exec {_L_bash_profile_fd}>"$1"
shift
%BEFORE%
trap 'if [[ ${__L_BASH_PROFILE_PID:-} != $BASHPID ]]; then trap "trap \"\" DEBUG; printf \"# %s %s %s %s %q %q %q\n\" \"\${EPOCHREALTIME//[.,]}\" \"\$BASHPID\" \"\${#BASH_SOURCE[@]}\" \"\${LINENO:-0}\" \"\${BASH_SOURCE[0]:-<}\" \"\${FUNCNAME[0]:->}\" EXIT >&\"$_L_bash_profile_fd\"" EXIT; __L_BASH_PROFILE_PID=$BASHPID; fi; printf "# %s %s %s %s %q %q %q\n" "${EPOCHREALTIME//[.,]}" "${BASHPID:-${BASH_SUBSHELL:-$$}}" "${#BASH_SOURCE[@]}" "${LINENO:-0}" "${BASH_SOURCE[0]:-<}" "${FUNCNAME[0]:->}" "$BASH_COMMAND" >&"$_L_bash_profile_fd"' DEBUG
%SCRIPT%
: END
""",
    "VAR": r"""
set -T
readonly _L_bash_profile_file=$1
shift
declare -a _L_bash_profile_var='()'
%BEFORE%
trap 'printf -v "_L_bash_profile_var[${#_L_bash_profile_var[@]}]" "# %s %s %s %s %q %q %q" "${EPOCHREALTIME//[.,]}" "${BASHPID:-${BASH_SUBSHELL:-$$}}" "${#BASH_SOURCE[@]}" "${LINENO:-0}" "${BASH_SOURCE[0]:-<}" "${FUNCNAME[0]:->}" "$BASH_COMMAND"' DEBUG
%SCRIPT%
printf "%s\n" "${_L_bash_profile_var[@]}" >"$_L_bash_profile_file"
""",
    "QEMU": r"""
kill -0 $$; kill -0 $$
set -T
%BEFORE%
trap 'kill -0 $$; printf "# %s %s %s %s %q %q %q\n" "0" "${BASHPID:-${BASH_SUBSHELL:-$$}}" "${#BASH_SOURCE[@]}" "${LINENO:-0}" "${BASH_SOURCE[0]:-<}" "${FUNCNAME[0]:->}" "$BASH_COMMAND" >&%FD%; kill -0 $$' DEBUG
%SCRIPT%
: END
""",
}
PROFILEMETHODS.update(
    {
        "1": PROFILEMETHODS["DEBUG"],
        "2": PROFILEMETHODS["XTRACE"],
        "3": PROFILEMETHODS["VAR"],
        "4": PROFILEMETHODS["QEMU"],
    }
)


@dataclass
class LineProcessor:
    """Processes lines from input file.
    Stores cached compile patterns.
    Synchronize with profiling bash script.
    """

    def process_line(self, data: list[tuple[int, str]]) -> list[Record]:
        # data = data if isinstance(data, list) else [data]
        ret: list[Record] = []
        for lineno, line in data:
            line = line.rstrip("\n")
            try:
                if line.startswith("# "):
                    # Fix shlex.split not able to parse $'\''
                    # line = line.replace(r"\'", "")
                    # arr = shlex.split(line)
                    arr = line.split(" ", 8)
                    rr = Record(
                        idx=lineno,
                        stamp_us=int(arr[1]),
                        pid=int(arr[2]),
                        cmd=" ".join(arr[7:]),
                        level=int(arr[3]) + 1,
                        lineno=int(arr[4]),
                        source=arr[5],
                        funcname=arr[6],
                    )
                    ret.append(rr)
                elif line.startswith("+"):
                    # Fix shlex.split not able to parse $'\''
                    # line = line.replace(r"\'", "")
                    # arr = shlex.split(line)
                    arr = line.split(" ", 8)
                    rr = Record(
                        idx=lineno,
                        stamp_us=int(arr[1]),
                        pid=int(arr[2]),
                        cmd=repr(" ".join(arr[7:])),  # arr[6],
                        level=int(arr[3]) + 1,  # len(arr[0]),
                        lineno=int(arr[4]),
                        source=arr[5],
                        funcname=arr[6],
                    )
                    ret.append(rr)
            except Exception:
                # print("ERROR: lineno:", lineno, " line:", repr(line), e)
                # raise
                # break
                continue
        return ret


@dataclass
class Analyzer:
    args: AnalyzeArgs
    records: list[Record] = field(default_factory=list)

    def run(self):
        with self.timeit(f"Reading {self.args.profilefile}"):
            self.read()
        with self.timeit("Calculating traces and time spent"):
            self.calculate_records_spent_time()

        if self.args.json:
            import json
            data = {
                "total_time": self.get_callgraph.totaltime,
                "commands": [
                    {
                        "cmd": cmd,
                        "spent": stats.spent,
                        "calls": len(stats.records),
                        "callers": dict(stats.callers),
                    }
                    for cmd, stats in sorted(
                        self.commands.items(), key=lambda x: x[1].spent, reverse=True
                    )
                ],
                "functions": [
                    {
                        "filename": func.filename,
                        "lineno": func.lineno,
                        "funcname": func.funcname,
                        "calls": stats.calls,
                        "spent": stats.spent,
                        "spent_exclusive": stats.spent_exclusive,
                    }
                    for func, stats in sorted(
                        self.functions.items(), key=lambda x: x[1].spent, reverse=True
                    )
                ],
            }
            print(json.dumps(data, indent=2))
            return

        with self.timeit("Getting longest commands"):
            self.print_top_longest_commands()
        with self.timeit("Getting longest functions"):
            self.print_top_longest_functions()
        self.print_tree()
        if self.args.dumprecords:
            self.dump_records(self.args.dumprecords)
        if self.args.callgraph:
            self.generate_dot_callgraph(self.args.callgraph)
        if self.args.callstats:
            self.generate_dot_callstats(self.args.callstats)
        if self.args.pstats:
            with self.timeit("Generting pstats file"):
                self.create_python_pstats_file(self.args.pstats)
        self.print_stats()

    def timeit(self, name: str):
        return Timeit(name if self.args.showtimes else "")

    def print_stats(self):
        totaltime = self.get_callgraph.totaltime
        if self.args.qemu:
            print(
                f"Script executed in {totaltime} instructions, {len(self.records)} instructions, {len(self.functions)} functions."
            )
        else:
            print(
                f"Script executed in {timedelta(microseconds=totaltime)}us, {len(self.records)} instructions, {len(self.functions)} functions."
            )

    def read(self):
        # read the data
        with self.args.profilefile as f:
            # Automatic format detection
            # Condensed QEMU traces start with # <high_number>
            # Standard traces start with # <timestamp>
            peek = f.readline()

            def line_gen():
                yield peek
                yield from f

            lp = LineProcessor()
            with multiprocessing.Pool() as pool:
                generator = asgroups(
                    maybe_take_n(enumerate(line_gen()), self.args.linelimit), 100
                )
                self.records = sorted(
                    flatten(pool.map(lp.process_line, generator)), key=lambda x: x.idx
                )

            # If the first record has a very large "timestamp" or if qemu flag is set,
            # it's likely instructions. Standard timestamps are > 1e15 (us since epoch).
            # Condensed QEMU start from 0 but quickly grow.
            # Actually, let's just trust the user flag or the fact that they used --qemu profile.
            # If we want auto-detection, we can check if spent_us values are "too small" for time but "just right" for instructions.
            # For now, let's keep self.args.qemu if it was set via CLI.

    def calculate_records_spent_time(self):
        # Group records by PID to calculate spent time correctly for concurrent processes
        by_pid = {}
        for rr in self.records:
            by_pid.setdefault(rr.pid, []).append(rr)

        for pid_records in by_pid.values():
            # Sort by index just in case, although they should already be sorted
            pid_records.sort(key=lambda x: x.idx)
            for i in range(len(pid_records) - 1):
                pid_records[i].spent_us = (
                    pid_records[i + 1].stamp_us - pid_records[i].stamp_us
                )
            # The last record of each PID has unknown spent_us
            # We could set it to 0 or leave it (it defaults to 0 in Record)
            pid_records[-1].spent_us = 0

    @cached_property
    def get_callgraph(self):
        callgraph = CallgraphNode()

        by_pid = {}
        for rr in self.records:
            by_pid.setdefault(rr.pid, []).append(rr)

        for pid, pid_records in by_pid.items():
            curnode = callgraph
            curlevel = 1
            for rr in pid_records:
                #
                if rr.level > curlevel:
                    # For new PID, level might start higher than 1 if it's a subshell
                    # But actually BASH_SOURCE depth starts at 1 usually.
                    # If it jumps, we should create intermediate nodes or just handle it.
                    for _ in range(rr.level - curlevel):
                        newnode = CallgraphNode(rr.function(), parent=curnode)
                        curnode.records.append(newnode)
                        curnode = newnode
                elif rr.level < curlevel:
                    for i in range(curlevel - rr.level):
                        if curnode.parent:
                            curnode = curnode.parent
                curlevel = rr.level
                curnode.records.append(rr)

        if self.args.filterfunction:
            funcnamergx = re.compile(self.args.filterfunction)
            callgraph2 = CallgraphNode()

            def traverse_to_filter(node: CallgraphNode):
                # print("MATCH", node.function.funcname, funcnamergx)
                if funcnamergx.match(node.function.funcname):
                    node.parent = callgraph2
                    callgraph2.records.append(node)
                else:
                    for rr in node.records:
                        if isinstance(rr, CallgraphNode):
                            # print(f"MATCH @ {rr.function}")
                            traverse_to_filter(rr)

            traverse_to_filter(callgraph)
            callgraph = callgraph2

        return callgraph

    def dump_records(self, file: str):
        with open(file, "w") as f:

            def traverse(node: CallgraphNode):
                f.write(f"{'  ' * node.level}{node.function}\n")
                for rr in node.records:
                    if isinstance(rr, CallgraphNode):
                        traverse(rr)
                    else:
                        f.write(f"{'  ' * (rr.level + 1)}{rr.cmd}\n")

            traverse(self.get_callgraph)

    @cached_property
    def commands(self) -> dict[str, CommandStats]:
        cmds: dict[str, CommandStats] = {}

        def traverse(node: CallgraphNode):
            for rr in node.records:
                if isinstance(rr, Record):
                    if rr.cmd not in cmds:
                        cmds[rr.cmd] = CommandStats()
                    cmds[rr.cmd].add(rr)
                else:
                    traverse(rr)

        traverse(self.get_callgraph)
        return cmds

    @cached_property
    def functions(self) -> dict[FunctionKey, FunctionStats]:
        funcs: dict[FunctionKey, FunctionStats] = {}

        def traverse(node: CallgraphNode):
            if node.function not in funcs:
                funcs[node.function] = FunctionStats()
            funcs[node.function].calls += 1
            funcs[node.function].spent += node.totaltime
            funcs[node.function].spent_exclusive += node.inlinetime

            def collect_records(n: CallgraphNode):
                for rr in n.records:
                    if isinstance(rr, Record):
                        funcs[node.function].records.append(rr)
                    else:
                        collect_records(rr)

            collect_records(node)

            for rr in node.records:
                if isinstance(rr, CallgraphNode):
                    traverse(rr)

        traverse(self.get_callgraph)
        return funcs

    def print_top_longest_commands(self):
        totaltime = self.get_callgraph.totaltime
        if totaltime == 0:
            return
        longest_commands = []
        for cmd, stats in sorted(
            self.commands.items(), key=lambda x: x[1].spent, reverse=True
        )[:10]:
            top_callers = sorted(
                stats.callers.items(), key=lambda x: x[1], reverse=True
            )[:3]
            longest_commands.append(
                {
                    "%": color.pct(f"{stats.spent / totaltime * 100:g}"),
                    "us": color.time(stats.spent),
                    "cmd": color.func(dots_trim(cmd, width=40)),
                    "calls": len(stats.records),
                    "spent/call": color.time(f"{stats.spent / len(stats.records):g}"),
                    "caller1": color.func(getdefault(top_callers, 0, ("", ""))[0]),
                    "caller2": color.func(getdefault(top_callers, 1, ("", ""))[0]),
                    "caller3": color.func(getdefault(top_callers, 2, ("", ""))[0]),
                    "location": color.loc(stats.get_example()),
                }
            )
        print(color.style("Top 10 longest commands (total):", bold=True))
        print(tabulate(longest_commands, headers="keys"))
        print()

        longest_commands_per_call = []
        for cmd, stats in sorted(
            self.commands.items(),
            key=lambda x: x[1].spent / len(x[1].records),
            reverse=True,
        )[:10]:
            top_callers = sorted(
                stats.callers.items(), key=lambda x: x[1], reverse=True
            )[:3]
            longest_commands_per_call.append(
                {
                    "%": color.pct(f"{stats.spent / totaltime * 100:g}"),
                    "us": color.time(stats.spent),
                    "cmd": color.func(dots_trim(cmd, width=40)),
                    "calls": len(stats.records),
                    "spent/call": color.time(f"{stats.spent / len(stats.records):g}"),
                    "caller1": color.func(getdefault(top_callers, 0, ("", ""))[0]),
                    "caller2": color.func(getdefault(top_callers, 1, ("", ""))[0]),
                    "caller3": color.func(getdefault(top_callers, 2, ("", ""))[0]),
                    "location": color.loc(stats.get_example()),
                }
            )
        print(color.style("Top 10 longest commands (per call):", bold=True))
        print(tabulate(longest_commands_per_call, headers="keys"))
        print()

    def print_top_longest_functions(self):
        totaltime = self.get_callgraph.totaltime
        if totaltime == 0:
            return
        longest_functions = []
        for func, stats in sorted(
            self.functions.items(), key=lambda x: x[1].spent, reverse=True
        )[:10]:
            if not func.funcname:
                continue
            longest_functions.append(
                {
                    "%": color.pct(f"{stats.spent / totaltime * 100:g}"),
                    "incl": color.time(stats.spent),
                    "excl": color.time(stats.spent_exclusive),
                    "func": color.func(dots_trim(str(func), width=40)),
                    "calls": stats.calls,
                    "spent/call": color.time(f"{stats.spent / stats.calls:g}"),
                    "location": color.loc(stats.get_example()),
                }
            )
        if not longest_functions:
            print("No functions found")
            return
        print(click.style("Top 10 longest functions (total):", bold=True))
        print(tabulate(longest_functions, headers="keys"))
        print()

        longest_functions_per_call = []
        for func, stats in sorted(
            self.functions.items(),
            key=lambda x: x[1].spent / x[1].calls if x[1].calls else 0,
            reverse=True,
        )[:10]:
            if not func.funcname:
                continue
            longest_functions_per_call.append(
                {
                    "%": color.pct(f"{stats.spent / totaltime * 100:g}"),
                    "incl": color.time(stats.spent),
                    "excl": color.time(stats.spent_exclusive),
                    "func": color.func(dots_trim(str(func), width=40)),
                    "calls": stats.calls,
                    "spent/call": color.time(f"{stats.spent / stats.calls:g}"),
                    "location": color.loc(stats.get_example()),
                }
            )
        print(click.style("Top 10 longest functions (per call):", bold=True))
        print(tabulate(longest_functions_per_call, headers="keys"))
        print()

    def print_tree(self):
        root_node = self.get_callgraph
        if root_node.totaltime == 0:
            return

        def render(node: CallgraphNode, parent_total: int, prefix: str = "", is_last: bool = True):
            # Aggregate all identical children under this parent
            groups = defaultdict(list)
            for rr in node.records:
                if isinstance(rr, CallgraphNode):
                    groups[rr.function].append(rr)

            # Sort by total time per group
            aggs = sorted(
                [(f, sum(c.totaltime for c in g), g) for f, g in groups.items()],
                key=lambda x: x[1],
                reverse=True,
            )
            if self.args.treelimit:
                aggs = aggs[: self.args.treelimit]

            for i, (func, total, group) in enumerate(aggs):
                p = color.pct(f"{total / parent_total * 100:.1f}%") if parent_total > 0 else color.pct("N/A%")
                unit = "ins" if self.args.qemu else "us"
                stats = f" ({len(group)} calls, avg {color.time(int(statistics.mean(c.totaltime for c in group)))}{unit}, stddev {color.time(int(statistics.pstdev(c.totaltime for c in group)))}{unit})" if len(group) > 1 else ""

                last = i == len(aggs) - 1
                print(f"{prefix}{'└── ' if last else '├── '}{color.func(str(func))} {color.time(total)}{unit} {p}{stats}")

                # Recurse into the first child as representative for subtree structure
                # Only recurse if there's meaningful time to show
                if total > 0:
                    render(group[0], total, prefix + ("    " if last else "│   "), True)

        print(click.style(f"Call Tree{f' (top {self.args.treelimit} children)' if self.args.treelimit else ''}:", bold=True))
        if root_node.function.funcname:
            print(f"{color.func(str(root_node.function))} {color.time(root_node.totaltime)}{'ins' if self.args.qemu else 'us'} {color.pct('100.0%')}")
        render(root_node, root_node.totaltime, "", True)
        print()

    def generate_dot_callgraph(self, file: str):
        dot = Digraph(comment="Bash Callgraph")
        nodemap = {}

        def traverse(node: CallgraphNode):
            if node not in nodemap:
                nodemap[node] = str(len(nodemap))
                dot.node(nodemap[node], str(node.function))
            for rr in node.records:
                if isinstance(rr, CallgraphNode):
                    traverse(rr)
                    dot.edge(nodemap[node], nodemap[rr])

        traverse(self.get_callgraph)
        dot.render(file, view=False)

    def generate_dot_callstats(self, file: str):
        # 1. Sum up all times per function
        @dataclass
        class NodeStats:
            callcount: int = 0
            primitivecallcount: int = 0
            inlinetime: int = 0
            totaltime: int = 0
            children: dict[FunctionKey, NodeStats] = field(default_factory=dict)

        callstats: dict[FunctionKey, NodeStats] = {}

        def fillstats(node: CallgraphNode):
            if node.function not in callstats:
                callstats[node.function] = NodeStats()
            nodestats = callstats[node.function]
            nodestats.callcount += 1
            nodestats.primitivecallcount += 1
            nodestats.totaltime += node.totaltime
            nodestats.inlinetime += node.inlinetime
            for child in node.children.values():
                fillstats(child)
                if child.function not in nodestats.children:
                    nodestats.children[child.function] = NodeStats()
                childstats = nodestats.children[child.function]
                childstats.callcount += 1
                childstats.primitivecallcount += 1
                childstats.inlinetime += child.inlinetime
                childstats.totaltime += child.totaltime
                if child.function == node.function:
                    nodestats.totaltime -= child.totaltime

        # fillstats(self.get_callgraph) # This is not working because CallgraphNode has no children attribute

    def create_python_pstats_file(self, file: str):
        @dataclass
        class Pstatsnocallers:
            callcount: int = 0
            primitivecallcount: int = 0
            inlinetime: float = 0
            totaltime: float = 0

        @dataclass
        class Pstats(Pstatsnocallers):
            callers: dict[FunctionKey, Pstatsnocallers] = field(default_factory=dict)

        stats: dict[tuple[str, int, str], tuple[int, int, float, float, dict]] = {}

        for func, fstats in self.functions.items():
            # (filename, line, name) -> (cc, nc, tt, ct, callers)
            # callers is dict of (filename, line, name) -> (cc, nc, tt, ct)
            # times are in seconds
            stats[astuple(func)] = (
                fstats.calls,
                fstats.calls,
                us2s(fstats.spent),
                us2s(fstats.spent),  # This is wrong, should be total time
                {},
            )

        with open(file, "wb") as f:
            marshal.dump(stats, f)


@dataclass
class ProfileArgs:
    """Command line arguments"""

    output: Optional[io.FileIO] = clickdc.option(
        "-o",
        type=click.File("w", lazy=True),
        help="Output file for profiling information.",
    )
    method: str = clickdc.option(
        "-m",
        default="1",
        type=click.Choice(list(PROFILEMETHODS.keys()), case_sensitive=False),
        help="""
        Chooses the method to profile the script.
        1 or DEBUG uses trap DEBUG to output executed commands to a file.
        2 or XTRACE uses set -x with BASH_XTRACEFD and FD4 to output the commands.
        3 or VAR uses trap DEBUG to append commands to an array and then write it to a file on the end of execution.
        4 or QEMU uses QEMU User-Mode Emulation to count exact CPU instructions.
        DEBUG is the most reliable.
        XTRACE is the fastest, but set -x prints after expansions have been done to the command.
        VAR does not handle subshells.
        QEMU is the most precise (instruction level).
        """,
    )
    repeat: int = clickdc.option(
        "-n", default=1, help="Repeat the script n times joined with newlines."
    )
    before: str = clickdc.option(
        "-b",
        help="Commands to run before the script. Use to set up the environment.",
        default="",
        required=False,
    )
    dryrun: bool = clickdc.option(
        help="Do not run the script, just print the generated script."
    )
    qemu: bool = clickdc.option(
        help="Shortcut for --method QEMU. Uses QEMU User-Mode Emulation."
    )
    script: str = clickdc.argument()
    args: tuple[str, ...] = clickdc.argument(nargs=-1)


def _profile(args: ProfileArgs, quiet: bool = False):
    if args.qemu:
        args.method = "QEMU"
    profilefile = (
        "/dev/stdout"
        if not args.output or args.output == sys.stdout
        else args.output.name
    )
    script = "\n".join([args.script] * args.repeat)
    script = (
        PROFILEMETHODS[args.method]
        .replace("%BEFORE%", args.before)
        .replace("%SCRIPT%", script)
    )
    cmd = [*bash_cmd(), "-c", script, "bash", profilefile, *args.args]
    if args.method in ["4", "QEMU"]:
        with tempfile.TemporaryDirectory() as tmpdir:
            fifo = os.path.join(tmpdir, "fifo")
            os.mkfifo(fifo)

            drain_thread = threading.Thread(
                target=qemu_output_drain_fifo, args=(fifo, profilefile)
            )
            drain_thread.start()

            fifo_fd = os.open(fifo, os.O_WRONLY)
            try:
                # Replace FD placeholder in the script
                script = script.replace("%FD%", str(fifo_fd))

                cmd = [
                    "qemu-x86_64",
                    "-one-insn-per-tb",
                    "-d",
                    "exec,strace",
                    "-D",
                    fifo,
                    *bash_cmd(),
                    "-c",
                    script,
                    "bash",
                    profilefile,
                    *args.args,
                ]

                if args.dryrun:
                    print(" ".join(shlex.quote(x) for x in cmd))
                    return

                print(
                    f"PROFILING: {shlex.quote(args.script)} to {profilefile}",
                    file=sys.stderr,
                )
                subprocess.run(cmd, pass_fds=[fifo_fd], env=bash_cmd_env(),
                               stdout=subprocess.DEVNULL if quiet else None,
                               stderr=subprocess.DEVNULL if quiet else None)
            finally:
                os.close(fifo_fd)
                drain_thread.join()
    else:
        if args.dryrun:
            print(" ".join(shlex.quote(x) for x in cmd))
            return
        print(
            f"PROFILING: {shlex.quote(args.script)} to {profilefile}", file=sys.stderr
        )
        subprocess.run(cmd, env=bash_cmd_env(),
                       stdout=subprocess.DEVNULL if quiet else None,
                       stderr=subprocess.DEVNULL if quiet else None)

    print(f"PROFILING ENDED, output in {profilefile}", file=sys.stderr)


@click.group(
    help="""A powerful and easy-to-use command-line tool for profiling Bash scripts.""",
    epilog="""
Written by Kamil Cukrowski 2024. Licensed under GPLv3.
    """,
)
@click_help()
def cli():
    try:
        locale.setlocale(locale.LC_ALL, "")
    except locale.Error:
        pass


@cli.command(
    help="""
Compare the performance of multiple Bash code snippets.
""",
    epilog="""
\b
Examples:
  # Compare the performance of two different commands
  L_bash_profile compare 'echo "hello"' 'printf "hello\\n"'

\b
  # Compare performance using QEMU instruction count method with a common prefix
  L_bash_profile compare --qemu --prefix 'x=0' '((x++))' 'let x++' 'x=$((x+1))'

\b
  # Compare performance using wall-clock time and repeating each snippet 1000 times
  L_bash_profile compare --repeat 1000 'sleep 0.001' 'sleep 0.002'
""",
)
@click_help()
@clickdc.adddc("args", CompareArgs)
def compare(args: CompareArgs):
    compare_cmd(args)


@cli.command(
    help="""
Profiles a Bash script and generates a file with the execution trace.

The script has to run commands in the current execution environment.
Use `source ./script.sh` to run a script from a file.
""",
    epilog="""
\b
Examples:
  # Profile a simple command and analyze the output
  L_bash_profile profile -n10 'echo "hello world"' | L_bash_profile analyze

\b
  # Profile a more complex script with a variable
  L_bash_profile profile -n200 -b i=0 '((i)); [[ $i ]];' | L_bash_profile analyze

\b
  # Profile a script with functions
  L_bash_profile profile -n500 -b 'f() { "$@"; }; g() { "$@"; }; i=1' 'f eval "(($i))"; g test "$i" = 0;' | L_bash_profile analyze
""",
)
@click_help()
@clickdc.adddc("args", ProfileArgs)
def profile(args: ProfileArgs):
    _profile(args)


@dataclass
class RunArgs(AnalyzeArgs):
    # Overwrite profilefile from AnalyzeArgs to be optional
    profilefile: Optional[io.TextIOBase] = field(default=None)

    method: str = clickdc.option(
        "-m",
        default="1",
        type=click.Choice(list(PROFILEMETHODS.keys()), case_sensitive=False),
        help="""
        Chooses the method to profile the script.
        1 or DEBUG uses trap DEBUG to output executed commands to a file.
        2 or XTRACE uses set -x with BASH_XTRACEFD and FD4 to output the commands.
        3 or VAR uses trap DEBUG to append commands to an array and then write it to a file on the end of execution.
        4 or QEMU uses QEMU User-Mode Emulation to count exact CPU instructions.
        DEBUG is the most reliable.
        XTRACE is the fastest, but set -x prints after expansions have been done to the command.
        VAR does not handle subshells.
        QEMU is the most precise (instruction level).
        """,
    )
    repeat: int = clickdc.option(
        "-n", default=1, help="Repeat the script n times joined with newlines."
    )
    before: str = clickdc.option(
        "-b",
        help="Commands to run before the script. Use to set up the environment.",
        default="",
        required=False,
    )
    dryrun: bool = clickdc.option(
        help="Do not run the script, just print the generated script."
    )
    qemu: bool = clickdc.option(
        help="Shortcut for --method QEMU. Uses QEMU User-Mode Emulation."
    )
    script: str = clickdc.argument()
    args: tuple[str, ...] = clickdc.argument(nargs=-1)


@cli.command(
    help="""
Profiles and analyzes a Bash script in one go.
""",
)
@click_help()
@clickdc.adddc("args", RunArgs)
def run(args: RunArgs):
    with tempfile.NamedTemporaryFile(prefix="L_bash_profile_", suffix=".txt") as tmp:
        # 1. Profile
        p_args = ProfileArgs()
        p_args.output = io.FileIO(tmp.name, "w")
        p_args.method = args.method
        p_args.repeat = args.repeat
        p_args.before = args.before
        p_args.dryrun = args.dryrun
        p_args.qemu = args.qemu
        p_args.script = args.script
        p_args.args = args.args
        _profile(p_args, quiet=True)

        if args.dryrun:
            return

        # 2. Analyze
        a_args = AnalyzeArgs()
        for f in field_names(AnalyzeArgs):
            if hasattr(args, f):
                setattr(a_args, f, getattr(args, f))
        a_args.profilefile = open(tmp.name, "r")
        Analyzer(a_args).run()


def field_names(cls) -> list[str]:
    return [f.name for f in field_list(cls)]


def field_list(cls):
    from dataclasses import fields

    return fields(cls)


@cli.command(
    help="""
Analyzes a profile file and generates human-readable reports.
""",
    epilog="""
\b
Example:
  # Analyze a profile file and generate multiple reports
  L_bash_profile analyze profile.txt \\
    --dumprecords profile.records.txt \\
    --callgraph profile.callgraph.dot \\
    --callstats profile.callstats.dot \\
    --pstats profile.pstats \\
    --callstatscmds \\
    --dotlimit 3

\b
  # Real-world example: Profiling L_lib.sh
  L_bash_profile profile -o profile.txt 'export L_UNITTEST_UNSET_X=0; . ../L_lib/bin/L_lib.sh test' -m XTRACE
  L_bash_profile analyze profile.txt --filterfunction L_argparse --dotlimit 6
""",
)
@click_help()
@clickdc.adddc("args", AnalyzeArgs)
def analyze(args: AnalyzeArgs):
    Analyzer(args).run()


@cli.command(help="print pstats data")
@click.option("-r", "--raw", is_flag=True, help="Just print marshal file content")
@click.argument("file", type=click.File("rb", lazy=True))
@click_help()
def showpstats(raw: bool, file: io.FileIO):
    if raw:

        def sortthem(x: dict):
            return sorted(x.items())

        def printit(prefix, key, val):
            print(
                f"{prefix}{key[0]}:{key[1]}({key[2]})  cc={val[0]} nc={val[1]} tt={val[2]:f} ct={val[3]:f}"
            )

        stats = marshal.load(file)
        for key, val in sortthem(stats):
            printit("", key, val)
            for key2, val2 in sortthem(val[4] or {}):
                printit(" ^ ", key2, val2)
    else:
        ps = pstats.Stats(file.name)
        sortby = "cumulative"
        ps.strip_dirs().sort_stats(sortby).print_stats()


###############################################################################

if __name__ == "__main__":
    cli.main()
