on:
  - push
env:
  PYTHONUNBUFFERED: 1
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.9"
          cache-dependency-glob: "uv.lock"
      - name: Install QEMU
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static
      - name: Install package and test dependencies
        run: uv sync --all-extras
      - name: Run basedpyright
        run: uv run basedpyright
      - name: Run tests
        run: uv run pytest -sv

  pypi-publish:
    name: Upload release to PyPI
    needs: [test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: pypi
      url: https://pypi.org/p/L_bash_profile
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.9"
          cache-dependency-glob: "uv.lock"
      - name: Build the package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1